
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sprd_gallery3d_refocus_util_ArcSoftRefocus */

#ifndef _arcrealbokeh
#define _arcrealbokeh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sprd_gallery3d_refocusimage_arcrealtime_ArcRealBokeh
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sprd_gallery3d_refocusimage_arcrealtime_ArcRealBokeh_init
  (JNIEnv *, jobject);

/*
 * Class:     com_sprd_gallery3d_refocusimage_arcrealtime_ArcRealBokeh
 * Method:    unInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sprd_gallery3d_refocusimage_arcrealtime_ArcRealBokeh_unInit
  (JNIEnv *, jobject);

/*
 * Class:     com_sprd_gallery3d_refocusimage_arcrealtime_ArcRealBokeh
 * Method:    refocus
 * Signature: (III[B[B[BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sprd_gallery3d_refocusimage_arcrealtime_ArcRealBokeh_refocus
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif